cmd/deploy.go, cmd/init.go, cmd/init_test.go, cmd/remote.go, cmd/remote_test.go, cmd/util.go
:hourglass: **Status**: Ready For Review
:tickets: **Ticket(s)**: None
---
+ Fixed the config writer so that we can still mock `remote.Bootstrap` appropriately (it writes to disk in the middle of the call.
+ Added a new field to `Config`:
```go
// Config represents the current projects configuration.
type Config struct {
CurrentRemoteName string     `json:"name"`
CurrentRemoteVPS  *RemoteVPS `json:"remote"`
DaemonAPIToken    string     `json:"token"`
io.Writer         `json:"-"`
}
```
The `io.Writer` is used in the call `config.Write()`. It holds some file or buffer to write the configuration to (useful for testing).
+ Unexported some functions as well (sorry for the noise).
```go
go test ./cmd -cover
```
=> Hotfix the config writer; unexport initialization functions

README.md, client/init.go
:hourglass: **Status**: ready
:tickets: **Ticket(s)**: Closes #31 
---
- Fixes minor bug where `inertia init` does not properly detect existing inertia configuration and proceeds to overwrite it causing weird things to happen
```
go install
inertia init
inertia init
```
=> Properly detect existing inertia configuration

README.md, client/remote.go, cmd/remote.go
:hourglass: **Status**: redy redy
:tickets: **Ticket(s)**: Close #53 'inertia remote add' walkthrough
---
- Walkthrough for the 'remote add' command
- Left `port` as a flag... but maybe should make it part of the walkthrough? 🤔 
```
go install
inertia init
inertia remote add gcloud
```
=> 'inertia remote add' walkthrough

client/deploy.go, client/deploy_test.go, cmd/deploy.go, common/types.go, common/util.go, common/util_test.go, daemon/docker.go, daemon/handler.go, daemon/helper.go, daemon/logger.go, daemon/logger_test.go
:hourglass: **Status**: Ready
:tickets: **Ticket(s)**: Closes #37
---
- Stream Inertia daemon logs with `inertia local logs --stream`, or access most recent logs with `inertia local logs`
- Stream docker-compose logs or specific containers using `inertia local logs docker-compose` or `inertia local logs mycontainer` specifically
-Reworked logging, ~~though this is bugged right now:~~
~~https://github.com/ubclaunchpad/inertia/blob/rob/%2337-deployment-logs/daemon/handler.go#L196 doesn't seem to properly return the error to the client - I think its still floating around somewhere because if I run `inertia local up` again, the line that was supposed to be returned shows up in the container logs alongside the first log from the second call~~ 
FIXED as of 754d625, turns out a `newline` is …
=> Deployment Logs

.dockerignore, .gitignore, .travis.yml, Dockerfile, client/deploy.go, client/deploy_test.go, client/remote.go, common/types.go, common/util.go, daemon/docker.go, daemon/handler.go, daemon/helper.go, main.go, remote.go, remote_test.go
:tickets: **Ticket(s)**: Closes #83
---
- You can now specify which branch you want deployed when running `inertia remote add`
- Daemon will now pull/checkout/clone requested branches 
```bash
$ inertia remote add local
$ inertia local up
```
=> Branch deployment

Makefile, README.md
:tickets: **Ticket(s)**: Closes #143
---
* Added instruction on installing Inertia through `brew install` 🥇 thanks to @iKevinY and the new [UBC Launch Pad tap](https://github.com/ubclaunchpad/homebrew-tap) 😎 
* 🍒 Cherrypicked the README and Makefile changes from #139 
* No functional changes
```bash
$> brew install ubclaunchpad/tap/inertia
```
=> Homebrew distribution

.travis.yml, README.md
:tickets: **Ticket(s)**: Closes #186
---
Windows installation using [Scoop](http://scoop.sh)! The Launch Pad Scoop bucket is [here](https://github.com/ubclaunchpad/scoop-bucket). If you have a Windows device please try this out 👍 
Install [Scoop](http://scoop.sh), and then in Powershell:
```bash
scoop bucket add ubclaunchpad https://github.com/ubclaunchpad/scoop-bucket
scoop install inertia
inertia --help
```
I tried on my laptop, but the install was taking ages on free wifi (stuck at ~22% lol) so I gave up :p
=> Windows installation via Scoop

daemon/inertia/project/build.go, daemon/inertia/project/build_test.go, daemon/inertia/project/deployment.go, daemon/inertia/project/deployment_test.go, daemon/inertia/project/docker.go
:tickets: **Ticket(s)**: Closes #173
---
This PR refactors some of the build code, adds some tests, and changes the deploy process so that a build is allowed to complete before the old containers are shut down and the new containers are brought up.
Some new interfaces:
```go
// Builder builds projects and returns a callback that can be used to deploy the project.
type Builder func(*Deployment, *docker.Client, io.Writer) (func() error, error)
type containerStopper func(*docker.Client, io.Writer) error
```
```
make test-all
```
Also needs some further testing with real projects, since I'm not sure if container conflicts will come into play. There are tests, but I'm not sure how well they reflect real usage since no actual code changes occur.
=> Faster deploys

client/deployment.go, client/deployment_test.go, common/request.go, daemon/inertia/logs.go, daemon/web/client.js, daemon/web/common/encodeURL.js
:tickets: **Ticket(s)**: Closes #176 
---
- requests are now split into separate get/post functions in the `deployment.go` file
- GET requests now process query strings
- daemon endpoints updated accordingly
- changes are only relevant to the logging functionality
- run tests as usual
=> #176 querystring (for GET requests)

.github/CONTRIBUTING.md, Makefile, README.md
:tickets: **Ticket(s)**: Closes #209
---
This PR splits up dependencies installs into `make dev-deps` and `make prod-deps`. Contribution guide has been updated accordingly and slightly improved (link to GoDoc and fixed spelling, for example)
The old `make deps` is still available.
Also did a slight reordering of the README again.
Default install version is now `"test"` so you don't have to write `make RELEASE=test` each time
n/a
=> Improved setup and contribution guide

.dockerignore, Dockerfile, client/client.go, client/client_test.go, daemon/inertia/project/deployment.go, daemon/web/package-lock.json, daemon/web/package.json, remote.go
:tickets: **Ticket(s)**: Closes #202
---
This PR cleans up some bugs, mostly from `v0.4.0-rc1`, that made Inertia unusable. Oops. 😛 
- Fixed client creation failing (which caused the "no remote with name found" error)
- Fixed daemon version, project name, build type not being correctly assigned by the client
- ~Fixed new build procedure added from #196 not actually being enabled 😅~ ...this seems to be causing a new myriad of problems, will enable at a later date - rolled back for now (see #214)
- Fixed broken daemon builds caused by #208
- Locked npm dependencies and updated several that were out of date
```
make test
```
and run it through the local testing steps (see [here](https://github.com/ubclaunchpad/inertia/blob/master/.github/CONTRIBUTING.md#setting-up-a-testing-environment))
=> Bugfixes (v0.4.0-rc1)

.gitignore, .travis.yml, Makefile, daemon/inertiad/project/build.go, daemon/inertiad/project/docker.go, daemon/web/package-lock.json, daemon/web/package.json, test/docker_deps.sh, test/lint_deps.sh
:tickets: **Ticket(s)**: Closes #234
---
- Restructured Travis build stages
- Separated out the bootstrap tests into a separate jobs
- Removed "allowed failure" builds
- Lots of script changes to accommodate new pipeline
The whole build pipeline still takes about 15 mins, but most jobs finish in 5 minutes, so it won’t be taking up all of Travis’s concurrency slots
=> Improve travis speed

Makefile, deploy.go
:tickets: **Ticket(s)**: Closes #167 
---
Warn if your `inertia.toml` version doesn't match your CLI version:
```bash
bobbook:inertia robertlin$ inertia --version
[WARNING] Configuration version 'v0.4.0-rc2' does not match your Inertia CLI version 'test'
inertia version test
bobbook:inertia robertlin$
```
```bash
$ make cli
$ inertia init
$ make cli-tagged
$ inertia --help
```
=> Warn if configuration file version doesn't match CLI version

deploy.go
:tickets: **Ticket(s)**: Closes #239
---
- Stream all command output by default
- Add flag "-s" or "--short" that disables streaming
Run through the usual deployment steps, commands should stream by default
=> Stream commands by default, add option to use "short" version

common/git.go, common/git_test.go, deploy.go, local/git.go, local/git_test.go, local/storage.go, remote.go
:tickets: **Ticket(s)**: Closes #262
---
Most Inertia users will have git installed - no need to package a complete git implementation alongside the CLI. This change replaces previous go-git functions with shell commands.
make test (only unit test changes were made)
=> Remove go-git dependencies in CLI

common/request.go, deploy.go
:tickets: **Ticket(s)**: Closes #266
---
- Fix incorrect send destination
- Add `--dest` flag to specify where you want your file to go relative to project root
n/a
=> Fix config send, add --dest flag

.gitignore, client/ssh.go, deploy.go
Command is executed over SSH and does not interact with the containerized daemon - /app/host/ is inappropriate here
see https://github.com/ubclaunchpad/inertia/pull/270#issuecomment-399656231 - closes #271
I just used @brian-nguyen's configuration to send Inertia's `CONTRIBUTING.md` over to the bumper deployment
```
bobbook:inertia robertlin$ inertia aws send CONTRIBUTING.md
[WARNING] Configuration version 'latest' does not match your Inertia CLI version 'test'
File CONTRIBUTING.md has been copied to $HOME/inertia/project/CONTRIBUTING.md on remote aws
bobbook:inertia robertlin$ inertia aws ssh
[WARNING] Configuration version 'latest' does not match your Inertia CLI version 'test'
Last login: Sat Jun 23 08:16:08 2018 from 24.86.161.145
__|  __|_  )
_|  (     /   Amazon Linux AMI …
```
=> Deliver file to absolute path on host

.gitignore, common/util.go, config.go, deploy.go, env.go, local/storage.go, local/storage_test.go, main.go, remote.go, users.go
:tickets: **Ticket(s)**: Closes #273
---
- New `--config` flag + a hack to parse it during `init()` to specify config path
- Updated package `local` functions to take path as argument
Make two inertia configs:
```
inertia1.toml
inertia2.toml
```
set them up, then:
```
make inertia
inertia --config inertia1.toml remote ls
inertia --config inertia2.toml remote ls
```
=> Allow variable config path via --config flag

CONTRIBUTING.md
:tickets: **Ticket(s)**: Closes #285
---
slack post:
> about commits and PR's going forward - as we approach 1000 commits (lol) we might want to start being a bit more strict on commits and organization. my thoughts right now:
> * `squash` (join all commits in a PR into one commit) small, nuclear changes - probably stuff lt/eq 3 zenhub story points, as well as PRs with lots of "mistake" commits (`add back accidentally deleted file` or `wip wip` commits for example (I've kind of already started this with PRs with the `merge: squash` label)
> * do standard merge commits for bigger PRs (gt/eq 8 zenhub story points) to keep more granular history, since there might be multiple "steps" to these PRs and it's kinda useless to squash a PR that encompasses 20+ files into a single commit
>
> As for …
=> Add commit, merge, and branch guidelines

client/client.go, client/client_test.go, cmd/deploy.go, cmd/env.go, cmd/provision.go, cmd/users.go, common/util.go, local/storage.go, local/storage_test.go, provision/ec2.go
:tickets: **Ticket(s)**: Closes #193
---
No more straight `println` in package `client`. Made some minor refactors to accomodate this, as well as a new `common.DevNull` type (because `nil` pointers break everything)
run the CLI through its paces
=> Replace stdout prints with FPrint to set writers

CONTRIBUTING.md
:tickets: **Ticket(s)**: Closes #298
---
* 'client/bootstrap' is now 'client/scripts'
* add note that the docker daemon should be online
* add instructions for setting up GOPATH and GOBIN
just read it
=> Correct invalid references and add more detail to guide

client/client.go
:tickets: **Ticket(s)**: Closes #310
---
Adds some missing `\n`s to `Client.Bootstrap()` output that I didn't add in #294 oops
```bash
bobbook:inertia robertlin$ inertia local init
Setting up remote local at 127.0.0.1
>> Step 1/4: Installing docker...
>> Step 2/4: Building deploy key...
>> Step 3/4: Starting daemon...
Putting existing Inertia daemon to sleep
Downloading ubclaunchpad/inertia:latest
Running daemon on port 4303
>> Step 4/4: Fetching daemon API token...
Inertia has been set up and daemon is running on remote!
You may have to wait briefly for Inertia to set up some dependencies.
Use 'inertia local logs --stream' to check on the daemon's setup progress.
=============================
>> GitHub Deploy Key (add to https://www.github.com/ubclaunchpad/inertia/settings/keys/new): …
```
=> Add missing newlines to clean up bootstrap output

client/client.go, client/internal/compiled.go, client/scripts/daemon-down.sh, client/scripts/inertia-down.sh, cmd/config.go, cmd/deploy.go, cmd/env.go, cmd/provision.go, cmd/remote.go, cmd/users.go
:tickets: **Ticket(s)**: Closes #260 
---
Added a new command `inertia [remote] remove` that removes the `inertia/` directory as well as take down the daemon.
Test running a local project via 
```bash
$ inertia local init
$ docker exec -it testvps sh # Check that the inertia/ directory and docker subprocess are there
-> ls
inertia/
-> docker ps
some generic boring docker process output
$ inertia local remove
$ docker exec -it testvps sh # Check that the inertia/ directory and docker subprocess are gone
-> ls
-> docker ps
```
assuming these have ran in the background.
```bash
$ make
$ make testenv
$ make testdaemon
```
=> inertia [remote] remove

cmd/config.go, cmd/deploy.go, cmd/env.go, cmd/provision.go, cmd/remote.go, cmd/root.go, cmd/users.go, daemon/inertiad/cmd.go, daemon/inertiad/git/error.go, daemon/inertiad/project/deployment.go, doc.go
:tickets: **Ticket(s)**: Closes #308
---
Some tweaks to the wording, punctuation, casing, etc of the tooltips to better align with Cobra (the CLI library) standards
```bash
make cli
inertia # poke around commands
```
=> Clean up tooltips for consistency

daemon/inertiad/reset.go
:tickets: **Ticket(s)**: Closes #340
---
Don't point `deployment` to `nil` on reset. Null pointers galore
=> Don't reassign deployment

daemon/inertiad/containers/docker.go, daemon/inertiad/containers/docker_test.go
:tickets: **Ticket(s)**: Closes #343
---
b5f9bd34336f3078f635c873affee6916bdbe403 fixed the version to `1.37`, but then @brian-nguyen ran into incompatibilities straight away. This reverts back to creating client from env, but adds an additional step to hopefully negotiate the correct version.
This should be part of the standard `docker.NewClient` -_-
=> Create Client from ENV and negotiate API version from there

daemon/inertiad/project/data.go, daemon/inertiad/project/data_test.go
:tickets: **Ticket(s)**: Closes #342
---
`reset` clears the `env` bucket, which is great, but we need to recreate it
=> Recreate env bucket upon deleting

daemon/inertiad/build/builder.go, daemon/inertiad/build/output.go, daemon/inertiad/containers/containers.go, daemon/inertiad/containers/containers_test.go, daemon/inertiad/log/logger.go, daemon/inertiad/project/deployment.go, daemon/inertiad/prune.go
:tickets: **Ticket(s)**: Closes #351
---
See commits - biggest change is that ports exposed in Dockerfile images (via the `EXPOSE` directive) is now automatically mapped to host
build any dockerfile project, check that port is accessible
=> Dockerfile ports, containerstop fixes, minor updates

daemon/inertiad/build/builder.go, daemon/inertiad/build/builder_test.go, test/build/dockerfile/fail.Dockerfile
:tickets: **Ticket(s)**: Closes #349 
---
This was kind of unknowingly fixed by #365, just adjusted the messages a little and added a test to assert the behaviour
Run the updated test
=> Exit properly if image build fails

.scripts/release.sh, .travis.yml, Makefile, cmd/deploy.go, cmd/root.go, inertia.go, inertia_test.go
:tickets: **Ticket(s)**: Closes #367
---
Instead of hacky setting it from `main.Version`... just set `cmd.Version` directly. Oops
```bash
bobbook:inertia robertlin$ make cli RELEASE=chicken
go install -ldflags "-X github.com/ubclaunchpad/inertia/cmd.Version=chicken"
bobbook:inertia robertlin$ inertia --version
[WARNING] Configuration version 'latest' does not match your Inertia CLI version 'chicken'
inertia version chicken
```
=> Inject version var directly into package cmd

client/client.go, client/client_test.go, cmd/deploy.go, common/request.go, daemon/inertiad/containers/containers.go, daemon/inertiad/containers/containers_test.go, daemon/inertiad/logs.go
:tickets: **Ticket(s)**: Closes #358
---
- Adds a new `--entries` flag, defaults to 500 daemonside
```
inertia local up
inertia local logs --entries 10
inertia local logs --entries 1000
```
=> Add flag to set lines of logs to fetch

.appveyor.yml, .travis.yml, Dockerfile, Makefile
Travis has been pretty consistently failing all the time for no good reason, seemingly on `dep ensure` (though sometimes on loading cache). This changes all `dep ensure` commands to run with the `-v` flag which provides more detailed outputs, for potential debugging purposes.
```
make deps
```
=> Run all dep ensure commands with -v flag

.appveyor.yml, local/git_test.go
CI typically checkouts exact commits (detached mode), which breaks the `git branch` test. I previously added a workaround for this for Appveyor (#361), which breaks reproducibility of tests. 
However, I just noticed that this was straight up disabled for Travis - which is probably the best approach. This PR removes the workaround and disabled the test on both Travis and Appveyor.
=> Disable git branch test on CI, remove Appveyor workaround

README.md, daemon/inertiad/crypto/verify.go, daemon/inertiad/crypto/verify_test.go, daemon/inertiad/webhook.go, daemon/inertiad/webhook/bitbucket.go, daemon/inertiad/webhook/github.go, daemon/inertiad/webhook/gitlab.go, daemon/inertiad/webhook/parse.go, daemon/inertiad/webhook/parse_test.go, daemon/inertiad/webhook/verify.go, daemon/inertiad/webhook/verify_test.go, daemon/inertiad/webhook_test.go
:tickets: **Ticket(s)**: Closes #390
---
- Refactor webhook parsing to accomodate new `webhook.Verify()` step
- New package `crypto` function for HMAC signature validation
- Use HMAC verification where appropriate (GitHub, some BitBucket)
- based off of go-github's implementation - similar tests pass, so hopefully it is correct
- Use simple token verification for GitLab as per documentation
```
make test
```
=> Refactor webhook parsing, implement payload verification

.travis.yml, Makefile, daemon/inertiad/auth/users.go
:tickets: **Ticket(s)**: Closes #411
---
Removed go-metalinter which sucked
Added go vet, golint, etc. We lose on some of the fancier static analysis stuff (no-ineff-assign, useless return checks, etc) but oh well.
```
make deps
make lint
```
=> Remove go-metalinter, use go vet, golint, etc.

client/client.go, client/client_test.go, cmd/deploy.go, cmd/users.go
:tickets: **Ticket(s)**: Closes #421 
---
@bobheadxi I marked this as WIP because I'm not sure we can actually merge this yet. With the functionality I've added, if you log in as a regular user while you hold the master token, that master token will be overwritten with the auth token for the user you logged in as. Is there a way to add regular credentials to the master account as-is, or will we need to implement that? 
- Added `LogIn` method to `users.go` that hits the `/user/auth` endpoint with the user's credentials and returns the response.
- Added tests for `LogIn()`.
- Added a `login` command that accepts the user's credentials (password is hidden and can't be specified as an argument) and uses them to retrieve an auth token. The `inertia.toml` config file is then updated with the …
=> [WIP] Allow clients to authenticate via the CLI

client/client.go
:tickets: **Ticket(s)**: Closes #444
---
Adds a brief warning that Content-Type for GitHub webhook must be JSON after providing it.
=> Add warning that GitHub webhook Content-Type must be JSON

CONTRIBUTING.md
---
SSH port [defaults to 69](https://github.com/ubclaunchpad/inertia/blob/master/Makefile#L2), this change updates instructions to reflect that
See docs
=> Add note about default testenv SSH port

daemon/inertiad/auth/permissions.go, daemon/inertiad/auth/permissions_test.go
Just updated the `disableTotp` endpoint so it doesn't require re-authentication like most other TOTP implementations.
=> Update disable totp

cmd/provision.go, provision/ec2.go, provision/ec2_test.go, test/aws/credentials
:tickets: **Ticket(s)**: Closes #439 
---
Fixes how users are handled on provisioner instantiation, and does some minor cleanup
```sh
go install
inertia provision ec2 myEC2Instance -p 8080 --profile-path ~/.aws/credentials
```
=> provisioning: ec2 fix

cmd/deploy.go
:tickets: **Ticket(s)**: Closes #410 
---
Reported daemon address was the old `http` address - the default behaviour is now to use `https`
n/a
=> Update reported daemon API address

.scripts/release.sh
:tickets: **Ticket(s)**: Closes #379 
---
Remove darwin/386, add darwin/amd64
Minor lint improvements of the release script
```
bash .scripts/release.sh
```
=> dist: build darwin/amd64 instead of darwin/386

cmd/remote.go
---
Noticed some minor inconsistencies in the spacing on this particular docstring
```
inertia remote
```
=> cmd: fix minor spacing inconsistencies

daemon/inertiad/git/git.go, daemon/inertiad/git/git_test.go, daemon/inertiad/project/deployment.go
:tickets: **Ticket(s)**: Closes #350
---
* Simplify repo update function signatures
* Make repo update more aggressive with tags, submodules, etc.
* Update clone procedure to respect existing files 
* Do not clear project directory on initialization
[same as usual](https://github.com/ubclaunchpad/inertia/blob/master/CONTRIBUTING.md#development-tips)
=> deploy: persist sent files

daemon/inertiad/auth/permissions.go, daemon/inertiad/auth/permissions_test.go, daemon/inertiad/crypto/password.go, daemon/inertiad/crypto/password_test.go
:tickets: **Ticket(s)**: Closes #458 
---
* Adds an error check function `IsCredentialFormatError` to check if an error is related to credential format, and returns a `400` (bad request) instead of `500`
Create a user with bad credentials
=> daemon: on user create, check if error is a bad cred error and return 400

client/client.go
:tickets: **Ticket(s)**: Closes #409
---
SSH -> SSL
n/a
=> cmd: fix typo in webhook documentation

client/client.go, client/client_test.go, client/integration_test.go, client/ssh.go, cmd/deploy.go, cmd/provision.go, local/env.go, local/storage.go
:tickets: **Ticket(s)**: Closes #408
---
This PR adds support for passphrase-protected keys via the `PEM_PASSPHRASE` environment variable
set env, try to use a passphrase-protected key
=> cmd: add support for passphrase-protected PEM keys

client/ssh.go, client/ssh_test.go, cmd/deploy.go
:tickets: **Ticket(s)**: Closes #441 
---
Dedicated to @rwblickhan 
* reimplement SSH session run as a direct exec of `ssh`
Things now exit properly:
```
~/go/src/github.com/ubclaunchpad/inertia cmd/#441-ssh
❯ ./inertia local ssh
Welcome to Ubuntu 18.04.1 LTS (GNU/Linux 4.9.125-linuxkit x86_64)
* Documentation:  https://help.ubuntu.com
* Management:     https://landscape.canonical.com
* Support:        https://ubuntu.com/advantage
This system has been minimized by removing packages and content that are
not required on a system that users do not log into.
To restore this content, you can run the 'unminimize' command.
Last login: Sun Jan  6 02:11:08 2019 from 172.17.0.1
root@fe00995ac4f3:~# ^C
root@fe00995ac4f3:~# exit
logout
Connection to 127.0.0.1 closed.
2019/01/05 18:13:50 exit status …
```
=> cmd: fix interactive SSH sessions

client/client.go, client/client_test.go, cmd/config.go, cmd/deploy.go, cmd/users.go
:tickets: **Ticket(s)**: Closes #491
---
* `inertia [remote] upgrade [-v version]`
* `inertia upgrade [-v version]`
see above commands
=> cmd: basic upgrade commands

cmd/config/config.go, cmd/host/env.go, cmd/host/host.go, cmd/host/user.go, cmd/provision/provision.go, cmd/remote/remote.go, cmd/root.go
---
Replaces direct string key retrieval with variables denoting flag keys
all commands should work as before
=> cmd: use flag key variables instead of plain strings

.dockerignore, Dockerfile
:tickets: **Ticket(s)**: Closes #512
---
- Web dependency installs (via npm) now occur in its own stage
- Go dependency installs (via dep) now occur in its own stage
Try:
```
make testdaemon-image
```
Subsequent builds with minor code changes should now benefit from improved stage caching => better build times 😄
=> dist: separate dockerfile stages for dependency installs

client/client.go, client/client_test.go
:tickets: **Ticket(s)**: Closes #526 
---
add error checking on client.LogsWebSocket + test
make test
=> cmd: check for errors on log websockets

client/client_test.go
:tickets: **Ticket(s)**: Closes #526 
---
fix https://github.com/ubclaunchpad/inertia/pull/533#issuecomment-461286647
make test
=> fix log websocket test

cmd/provision/provision.go
---
The default profile path was incorrect
set up credentials in `~/.aws/credentials` (https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html)
```
inertia provision ec2 --from-profile blah
```
region listing should work as authentication is used
=> provision: fix default aws credentials path

Gopkg.lock, api/api.go, api/response.go, api/response_test.go, cmd/host/env.go, cmd/host/host.go, cmd/host/user.go, cmd/host/user_totp.go, daemon/inertiad/auth/permissions.go, daemon/inertiad/auth/permissions_test.go, daemon/inertiad/auth/sessions.go, daemon/inertiad/auth/users.go, daemon/inertiad/daemon/down.go, daemon/inertiad/daemon/env.go, daemon/inertiad/daemon/logs.go, daemon/inertiad/daemon/prune.go, daemon/inertiad/daemon/reset.go, daemon/inertiad/daemon/status.go, daemon/inertiad/daemon/token.go, daemon/inertiad/daemon/token_test.go, daemon/inertiad/daemon/up.go, daemon/inertiad/daemon/webhook.go, daemon/inertiad/log/logger.go, daemon/inertiad/log/logger_test.go, daemon/inertiad/log/streamer.go, daemon/inertiad/log/streamer_test.go, daemon/inertiad/res/base.go, daemon/inertiad/res/doc.go, daemon/inertiad/res/error.go, daemon/inertiad/res/message.go
:tickets: **Ticket(s)**: Closes #502 
---
* [chi ](https://github.com/go-chi/chi) + middleware for routing needs
* basic JSON structure for as many things as I could update without demolishing things (package `api` and package `res`)
* update CLI and stuff as much as possible without radical changes
Here's the idea - all responses should be structured like this:
```go
// BaseResponse is the underlying response structure to all responses.
type BaseResponse struct {
// Basic metadata
HTTPStatusCode int    `json:"code"`
RequestID      string `json:"request_id,omitempty"`
// Message is included in all responses, and is a summary of the server's response
Message string `json:"message"`
// Error contains additional context in the event of an error
Error string `json:"error,omitempty"`
// Data …
```
=> daemon: JSON responses for API

.scripts/build_docs.sh
:tickets: **Ticket(s)**: Closes #559 
---
Forcibly write CNAME after doc build. See #559 for details
```
make docs
```
CNAME should still be there after
=> chore: write to CNAME after build

daemon/inertiad/crypto/token.go
mster -> master
:tickets: **Ticket(s)**: Closes #564 
---
Typo fix
Is it spelt correctly?
=> Update token.go to fix typo

cmd/remotes/remotes.go
:tickets: **Ticket(s)**: Closes #580 
---
A utility function on the host command was calling itself, making things blow up. See #580 for details
```
inertia ${remote_name} init
```
=> cmd: fix recursive getRemote()

CONTRIBUTING.md, docs/tip/cli/README.md, docs/tip/cli/inertia_remote_upgrade.md, docs/tip/index.html, docs_src/index.html.md
:tickets: **Ticket(s)**: Closes #581
---
* update usage guide for new config format and commands
* update CONTRIBUTING for new commands
* misc wording improvements
```
make run-docs-usage
```
=> docs: update for new config format and commands

cmd/core/utils/output/format.go, cmd/project/profile.go, cmd/remote/remote.go, docs/tip/cli/README.md, docs/tip/cli/inertia_remote_upgrade.md, docs/tip/index.html, docs_src/index.html.md
---
* fixed config command in docs (missed in #587 )
* fix remote upgrade
* removed `-r`, just use variable args
* fix remote deletion
* you can now `rm` more than one remote at a time
```
make cli
./inertia remote show ... # should now include version
./inertia upgrade --all
./inertia rm ...
```
=> cmd: fix remote management

cmd/core/utils/output/print.go, cmd/remote/remote.go, cmd/remotes/remotes.go, cmd/root.go
:tickets: **Ticket(s)**: Closes #591
---
Adding a remote first checks if the remote is also a command name
```
❯ ./inertia remote add remote
'remote' is the name of an Inertia command - please choose something else
```
=> cmd: prevent command names from being used as remotes

Gopkg.lock, Gopkg.toml, cmd/core/utils/out/decor.go
:tickets: **Ticket(s)**: related to #595 
---
My PR was merged upstream (https://github.com/kyokomi/emoji/pull/32), so we can switch back to original library now
Also I deleted my fork so Travis is failing lol https://travis-ci.org/ubclaunchpad/inertia/builds/501923028
run tests
=> cmd: switch back to kyokomi/emoji

local/init.go, local/storage.go
:tickets: **Ticket(s)**: Closes #600
---
* use `os.ModePerm` instead of `0400` when creating config files
```
inertia init --global
inertia remote ls # should not say something about permissions
```
=> local: use os.ModePerm when writing config files

api/api.go, cfg/remote.go, client/client.go, cmd/host/host.go, daemon/inertiad/daemon/up.go, daemon/inertiad/project/deployment.go
:tickets: **Ticket(s)**: for #607 
---
* in your config, manually add a field under remote configuration:
```toml
dont-kill-on-death = true
```
then `up`
more context in ticket. something like this will need to be separately implemented for what's on `master`
as above
=> config: hack in an ignore-death option

.appveyor.yml, .travis.yml
:tickets: **Ticket(s)**: for #611 
---
Bump CI/CD to use go1.13
=> chore: use go1.13 in CI

CONTRIBUTING.md, cmd/remote/remote.go, cmd/root.go, local/storage.go
:tickets: **Ticket(s)**: for #611
---
* use the new [`UserConfigDir`](https://github.com/golang/go/issues/29960) in the standard library to put global Inertia config in
* `inertia remote config-path` to show where stuff is going
* minor update to contributing docs to reflect changes
```
❯ ./inertia init --global
global Inertia configuration intialized at /Users/robertlin/Library/Application Support/inertia/inertia.global
❯ ./inertia remote config-path                                                   
global configuration directory: '/Users/robertlin/Library/Application Support/inertia'
global configuration path:      '/Users/robertlin/Library/Application Support/inertia/inertia.global'
```
=> local: use go1.13 UserConfigDir for InertiaDir

.github/workflows/publish-release.yml, client/bootstrap/bootstrap_test.go
:tickets: **Ticket(s)**: follow-up to #628 
---
It seems that the new `Publish (release)` workflow triggers twice for pre-releases - this PR amends that I think
I'll cut another release later
=> ci: only run Publish(release) on 'published' event, silence bootstrap test log

daemon/inertiad/auth/users.go, daemon/inertiad/auth/users_test.go
:tickets: **Ticket(s)**: n/a - potential vulnerability reported by @Luxi-Zhao and co.
---
Removed the following behaviour outlined by @Luxi-Zhao 's report:
> unsafe handling of repeated failed login attempts by deleting the account in question after 10 attempts
=> daemon(auth): address unsafe handling of repeated failed login attempts

provision/ec2.go
:tickets: **Ticket(s)**: Closes #633
---
Filters out `ECS` images from EC2 provisioning recommendations
=> provision(ec2): filter out ECS images from recommendations

daemon/inertiad/daemon/up.go, daemon/inertiad/log/streamer.go
:tickets: **Ticket(s)**: Closes #626
---
Make container update failure a non-critical error to avoid failing a build
=> daemon: log history update as non-critical failure

cmd/remote/remote.go, cmd/remotes/remotes.go
:tickets: **Ticket(s)**: Closes #549 
---
```sh
./inertia test token --help 
```
Also removed the requirement for a project to be set up before accessing remotes.
=> cmd(remotes): add ability to generate token over SSH

docs/tip/cli/README.md, docs/tip/cli/inertia_remote_upgrade.md, docs/tip/index.html, docs_src/index.html.md
:tickets: **Ticket(s)**: Closes #627
---
Remove `go get` recommendation, rebuild docs
=> docs(tip): remove 'go get' recommendation

daemon/inertiad/auth/users.go, daemon/inertiad/auth/users_test.go
:tickets: **Ticket(s)**: Closes #550
---
* Fixes `inertia [remote] users reset` deleting the "sudo" `master` user
=> daemon(auth): only drop non-master users on reset

Makefile, api/api.go, cfg/project.go, client/client.go, daemon/inertiad/daemon/up.go, daemon/inertiad/notify/mocks/notify.go, daemon/inertiad/notify/notifier.go, daemon/inertiad/notify/notifier_test.go, daemon/inertiad/notify/slack.go, daemon/inertiad/notify/slack_test.go, daemon/inertiad/project/deployment.go, daemon/inertiad/project/deployment_test.go
:tickets: **Ticket(s)**: Closes #621 
---
* chore: fix counterfeiter runner
* daemon(notify): add equality checker 
* daemon(deployment): integrate slack config
There are unit tests, set up slack workspace to try it out - see #585
=> daemon(deployment): integrate slack config

docs/cli/README.md, docs/index.html, docs_src/index.html.md
---
Adds annotation layer via https://hypothes.is/ because... why not I guess?
/cc @srijonsaha
=> docs: add annotation layer on usage site

cmd/remotes/remotes.go
---
Fix bug with upgrading Inertia version.
=> cmd(remotes): save version after upgrading inertia remote

Dockerfile, daemon/inertiad/build/builder.go, daemon/inertiad/build/builder_test.go, daemon/inertiad/cfg/config.go, daemon/inertiad/cfg/config_test.go, daemon/inertiad/containers/images.go, daemon/inertiad/containers/images_test.go, test/daemon.env, test/docker_deps.sh
:tickets: **Ticket(s)**: Closes #665 
---
* daemon(containers): exclude prerelease images 
* daemon(all): get docker/compose dynamically or use latest
=> daemon: get docker-compose release dynamically

.dockerignore, .github/workflows/publish-latest.yml, .github/workflows/publish-release.yml, .scripts/release.sh, Makefile
---
Adds a publish step for GitHub Container Registry as a fallback (since Docker Hub limits are getting reduced)
not sure if we should migrate wholesale yet, but oh well
n/a
=> chore: publish to github container registry as well

.github/workflows/pipeline.yml
---
This was changed in #692, but seems to mess up our coverage records since the results do not get merged correctly with the unit test results by Codecov.
=> chore: target all packages when running integration tests

cmd/remote/remote.go
:tickets: **Ticket(s)**: Closes #697 
---
Adds `inertia remote import` to import existing remote configuration
=> cmd: add 'remote import'

daemon/inertiad/build/builder_test.go
---
Seems this test might be occasionally flakey
=> daemon(build): increase wait time in integration test

client/README.md, client/bootstrap/bootstrap_test.go, client/client.go, client/client_test.go, cmd/provision/provision.go, cmd/remote/remote.go, cmd/remotes/remotes.go
Since the switch to the new container registry (#692), the bootstrap script will no longer correctly work with pre-0.6.2 images. This change adds a check that requires newer images in remote configuration.
For context, we published an `v0.6.2` image: https://github.com/orgs/ubclaunchpad/packages/container/inertiad/93246
=> client: enforce a minimum daemon version
