ubclaunchpad/inertia

- .coveralls.yml
- .travis.yml
- README.md
:hourglass: **Status**: Ready for review
:tickets: **Ticket(s)**: #60 
---
A badge to remind us we have a coverage problem :+1:
> Add goveralls

- README.md
:hourglass: **Status**: Ready
:tickets: **Ticket(s)**: #88
---
Simplified setup documentation in the README and reduced the size of the logo slightly
n/a
> Simplify README documentation

- .github/CODEOWNERS
Over this summer, Mr John @PiggySpeed will be helping me out as a co-lead for this project 🎉 
This change simply adds John as a default reviewer. Enjoy the free notifications!
> Add new CODEOWNER

- client/client.go
- client/client_test.go
- deploy.go
- env.go
- local/storage.go
- users.go
:tickets: **Ticket(s)**: Closes #225
---
- Add '--verify-ssl' flag on relevant commands to enable certificate verification
if you run with `--verify-ssl` HTTP commands should fail
> Add '--verify-ssl' flag to enable certificate verification

- daemon/web/index.html
:tickets: **Ticket(s)**: Closes #283
---
Add fontawesome via cdn!
none
> Add fontawesome

- .travis.yml
:tickets: **Ticket(s)**: Closes #303
---
Bye bye coveralls, hello codecov
> Report coverage to codecov.io

- .codecov.yml
> Add coverage configuration

- daemon/web/package-lock.json
- daemon/web/package.json
- daemon/web/webpack.config.js
---
Adjusts the webpack config to allow inline SVGs.
N/A
> added inline svg processing to config

- cmd/format.go
- cmd/input.go
- daemon/inertiad/build/builder_test.go
:tickets: **Ticket(s)**: Closes #338
---
Prompt for input, update leftover `[VPS]` reference to `[remote]`
> Prompt for input for build config, update msgNoDeployment remote var

- codecov.yml
The path flags don't seem to be working - either fix here, or remove entirely.
> Codecov fixes

- daemon/inertiad/project/deployment.go
:tickets: **Ticket(s)**: Closes #370
---
Adds some `d.active = false`
> Set active to false before stopping containers

- README.md
Discussed this with @bobheadxi over email.
> Added hall-of-fame to README

- daemon/inertiad/webhook.go
- daemon/inertiad/webhook/bitbucket_push.go
- daemon/inertiad/webhook/github_push.go
- daemon/inertiad/webhook/gitlab_push.go
- daemon/inertiad/webhook/webhook.go
- daemon/inertiad/webhook/webhook_test.go
:tickets: **Ticket(s)**: Closes #377
---
Reduces webhook outputs significantly, down to a max of 2 log entries each
> Reduce webhook output

- Dockerfile
- README.md
- cmd/config.go
- cmd/input.go
- cmd/input_test.go
- common/util.go
- common/util_test.go
- daemon/inertiad/build/builder.go
- daemon/inertiad/build/builder_test.go
- daemon/inertiad/cfg/config.go
- daemon/inertiad/containers/containers_test.go
- daemon/inertiad/daemon.go
- test/daemon.env
- test/docker_deps.sh
:tickets: **Ticket(s)**: Closes #324
---
Herokuish is slow af, generates huge images, and doesn't really seem worth maintaining - this PR deprecates Herokuish builds entirely.
Should also speed up our travis builds...
> Deprecate Herokuish builds

- daemon/web/components/NavBar/index.js
- daemon/web/components/NavBar/index.sass
- daemon/web/styles/decoration.sass
- daemon/web/styles/index.sass
- daemon/web/styles/typography.sass
:tickets: **Ticket(s)**: Closes #241
---
Nav bar styles.
Still need to work on logout button styling.
> Style Nav bar

- daemon/web/components/NavBar/index.js
- daemon/web/components/buttons/LogoutButton/index.js
- daemon/web/components/buttons/ShutdownButton/index.js
---
Logout button on the nav (as a component) without global styling
> Logout button on Nav

- daemon/web/components/IconHeader/index.js
- daemon/web/components/IconHeader/index.sass
- daemon/web/components/Status/index.js
- daemon/web/components/Status/index.sass
- daemon/web/components/TerminalView/index.js
- daemon/web/components/TerminalView/index.sass
- daemon/web/components/buttons/index.sass
- daemon/web/pages/Containers/index.js
- daemon/web/pages/Containers/index.sass
- daemon/web/pages/Dashboard/index.js
- daemon/web/pages/Settings/index.js
- daemon/web/styles/decoration.sass
- daemon/web/styles/spacing.sass
- daemon/web/styles/utils.sass
---
Made styling changes to all the pages to make them all look consistent.
> Web/#384 Consistent global styles

- .gitignore
- daemon/inertiad/crypto/totp.go
- daemon/inertiad/crypto/totp_test.go
:tickets: **Ticket(s)**:  regarding #417
---
- Adds TOTP secret generation/validation
- Adds backup code generation using same format as Github (e.g. "b2e03-ffbcf")
- TOTP secret generation parameters are compatible with Google Authenticator
See: totp_test.go
> adds TOTP generation, validation, and backup codes

- README.md
:tickets: **Ticket(s)**: Closes #427
---
Switch Google Drive links to slides.ubclaunchpad.com
n/a
> Switch Google Drive links to slides.ubclaunchpad.com

- Gopkg.lock
- daemon/inertiad/crypto/totp.go
- daemon/inertiad/crypto/totp_test.go
---
Just some lint errors (making some things private, sorting imports, etc.)
n/a
> Lint totp.go, lock dependencies

- cmd/deploy.go
- cmd/users.go
- daemon/inertiad/auth/permissions.go
:tickets: **Ticket(s)**: Closes #433 
---
Chang all the bad auth status to http.StatusUnauthorized
> Correct the HTTP status

- client/client.go
- cmd/users.go
- daemon/inertiad/auth/permissions.go
- daemon/inertiad/auth/users.go
- Fixed a bug in the client implementation of `disableTotp` (it should take no arguments because the user is authenticated user his/her access token)
- Fixed some minor code smells
> Update distable totp

- Gopkg.lock
- Gopkg.toml
- cmd/config.go
- cmd/deploy.go
- cmd/env.go
- cmd/provision.go
- cmd/remote.go
- cmd/users.go
:tickets: **Ticket(s)**: Closes #300
---
We don't really need a library as robust as logrus in the command line part of Inertia
n/a
> Remove logrus

- cmd/root.go
---
Small typo i just noticed
n/a
> Fix grammatical error

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature-idea.md
New GitHub features: https://blog.github.com/changelog/2018-12-05-issue-template-automation-improvements/
> Update issue templates

- daemon/inertiad/up.go
:tickets: **Ticket(s)**: Closes #454
---
Adds a call to `deployment.SetConfig` applying changes from an `up` request
up, change config, then up again!
> daemon: apply project config changes on 'up'

- .appveyor.yml
- .travis.yml
:tickets: **Ticket(s)**: Closes #415
---
go1.10 -> go1.11
n/a
> chore: bump to go 1.11

- daemon/inertiad/auth/users.go
:tickets: **Ticket(s)**: Closes #460
---
* minor cleanup of credential check
* bump threshold to 10
try logging in inccorrectly
> daemon: increase account deletion threshold

- provision/ec2.go
:tickets: **Ticket(s)**: Closes #500
---
Added stricter options when listing images:
* only `ebm`, `hvm` images as noted by @rwblickhan in #500 
* additional restrictions:
* `machine`, `x86`, just in case
The official AWS documentation is [here](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-images.html)
Hopefully no invalid images are listed anymore on `inertia provision ec2 [name]`
```
go build
./inertia provision ec2 russell
```
> provision: stricter requirements when listing ec2 image options

- daemon/inertiad/daemon/doc.go
- daemon/inertiad/util/doc.go
> docs: add godocs for daemon, util

- client/client.go
- cmd/host/host.go
- daemon/inertiad/log/logger.go
- daemon/inertiad/log/writers.go
- daemon/inertiad/project/data.go
:tickets: **Ticket(s)**: Closes #404 
---
Replace `http` status code with `websocket` status code
see #404
> daemon: use code websocket.CloseNormal, minor fixes

- daemon/inertiad/project/deployment.go
---
On deployment init, remove `.git`
```
inertia local up
inertia local upgrade
inertia local up
```
> Remove preexisting git repos on init

- cmd/host/host.go
- daemon/inertiad/daemon/daemon.go
---
Attach command forgotten in #511 
`inertia [remote] prune`
> cmd: attach prune command

- README.md
---
Slight update to `Main Features` section
read the readme
> docs: README refresh

- Gopkg.lock
- Gopkg.toml
- local/storage.go
- provision/ec2.go
---
Fixes provisioning region assignment
Updates the AWS SDK
Write key with perm 0400
using a region other than `us-east-1` should work
> provision: fix ec2 region assignment, key perms

- CONTRIBUTING.md
> Fixed Ubuntu version spelling mistake

- .github/CODEOWNERS
> chore: add inertia team to CODEOWNERS

- CONTRIBUTING.md
Fixed the broken link leading to usage documentation website
---
Updated contributing guide broken link
NA
> Update contributing guide broken link

- .appveyor.yml
- .travis.yml
:tickets: **Ticket(s)**: for #570 
---
* bump travis to go1.12
* bump appveyor to go1.12
see CI results
> chore: bump to go1.12

- client/README.md
- client/bootstrap/bootstrap.go
- client/bootstrap/bootstrap_test.go
- client/bootstrap/doc.go
- client/runner/doc.go
- client/runner/mocks/doc.go
- cmd/provision/provision.go
- cmd/remotes/remotes.go
---
* Clean up bootstrap script and bootstrap docs
* update client example
n/a
> client: clean up bootstrap, update docs and client example

- contrib/npm/.npmrc
- contrib/npm/package.json
:tickets: **Ticket(s)**: for #607 
---
* add `npmrc` so `NPM_TOKEN` can be used
* bump to `v0.5.3`
`npm install inertia-cli`
> contrib/npm: bump to v0.5.3

- .github/workflows/lsif.yml
refer to https://docs.sourcegraph.com/user/code_intelligence/lsif
---
I'm procrastinating and trying out the LSIF feature in Sourcegraph: https://docs.sourcegraph.com/user/code_intelligence/lsif
TODO
> chore: set up LSIF generation and upload

- README.md
:tickets: **Ticket(s)**: for #628 
---
fix the badge
> switch travis badge to github actions badge

- .github/workflows/lsif.yml
- .github/workflows/publish-latest.yml
- .github/workflows/publish-release.yml
:tickets: **Ticket(s)**: follow-up to #628 , #622
---
* fix publish jobs
* disable the sourcegraph action for LSIF upload
* there seems to be a new official action in the works: https://github.com/sourcegraph/lsif-upload-action, but it doesn't really work yet (getting unauthenticated errors and whatnot)
n/a
> ci: fix workflows

- README.md
---
* added mention of Rocket 2, Bumper, and the nwHackks 2019 website
* tweaked the wording of the blurb a little to change "simple" to "user-friendly" and mention Inertia's serverside component
n/a
> docs: inertia users and tweaked blurb

- cmd/project/project.go
- cmd/remote/remote.go
:tickets: **Ticket(s)**: Closes #596
---
Add `inertia remote reset`
also updates `inertia project reset` for consistency
> cmd(remote): add reset command

- .github/workflows/lsif.yml
---
A just-out-of-curiosity update to a previous attempt at trying out [Sourcegraph's LSIF setup](https://docs.sourcegraph.com/user/code_intelligence/lsif)
try some queries on sourcegraph
> chore: add lsif upload workflow

- cmd/remote/remote.go
:tickets: **Ticket(s)**: Closes #535
---
```
inertia remote login [remote] [user] [flags]
```
also added an alias, `inertia r`, for remote commands
> cmd(remote): add login command

- docs/tip/cli/README.md
- docs/tip/cli/inertia_remote_upgrade.md
- docs/tip/index.html
- docs_src/index.html.md
:tickets: **Ticket(s)**: follow-up to #655 , #654 
---
Adds a brief shoutout for the status badge feature
> docs(tip): document status badge feature

- .appveyor.yml
- .github/workflows/pipeline.yml
- .github/workflows/publish-release.yml
- CONTRIBUTING.md
- go.mod
:tickets: **Ticket(s)**: Closes #658 
---
Bump to go1.14
> chore: upgrade to go1.14

- api/response.go
- cmd/core/utils/out/format.go
- cmd/core/utils/out/format_test.go
- cmd/remotes/remotes.go
- daemon/inertiad/containers/images.go
- daemon/inertiad/containers/images_test.go
- daemon/inertiad/daemon/status.go
- go.mod
- go.sum
:tickets: **Ticket(s)**: Closes #84
---
* daemon(status): check for new version on `inertia {remote} status`
* cmd(remotes): fix version specification during upgrade
> daemon(status): inertia version check

- cfg/util.go
- cmd/project/project.go
---
Fixes `inertia project [set] [property]`
> cmd(project): fix set command

- cfg/project.go
- cfg/project_test.go
- cmd/remotes/remotes.go
:tickets: **Ticket(s)**: Closes #664 
---
Adds a new field, `version`, for tracking a min version, e.g. `version = v0.6.1` 
=> `>= v0.6.1 < v0.7.0`
Add cli-side version validation
> cmd: min version checks

- cmd/contrib.go
- cmd/remotes/remotes.go
- cmd/root.go
- contrib/inertia-completions/main.go
- contrib/inertia-docgen/main.go
- go.mod
- go.sum
- main.go
:tickets: **Ticket(s)**: Closes #443 
---
* upgrades to the newly released [cobra v1](https://github.com/spf13/cobra/releases/tag/v1.0.0)
* minor fix to how `contrib` plugins are loaded
* add plugin for generating plugins
> contrib(completions): cobra v1, inertia-completions, plugin fixes

- .github/workflows/lsif.yml
---
based on https://github.com/sourcegraph/sourcegraph/blob/master/.github/workflows/lsif.yml
n/a
> chore: fix lsif workflow

- CONTRIBUTING.md
- README.md
- cfg/README.md
- client/README.md
- cmd/README.md
- common/README.md
- docs/tip/cli/README.md
- docs/tip/cli/inertia_${remote_name}_upgrade.md
- docs/tip/cli/inertia_remote_upgrade.md
- docs/tip/index.html
- docs_src/index.html.md
- local/README.md
- provision/README.md
> docs: use official godev badge

- cfg/project.go
> cfg: remove constraint log

- docs/cli/README.md
- docs/cli/inertia_remote_upgrade.md
- docs/index.html
- docs/tip/cli/README.md
- docs/tip/cli/inertia_remote_upgrade.md
:tickets: **Ticket(s)**: for #690 
---
> release: v0.6.2

- .appveyor.yml
- .github/workflows/pipeline.yml
- .github/workflows/publish-release.yml
> chore: bump pipelines to go1.15

- daemon/inertiad/crypto/keys.go
- daemon/inertiad/crypto/keys_test.go
- daemon/inertiad/daemon/up.go
- daemon/inertiad/git/error.go
- daemon/inertiad/project/deployment.go
:tickets: **Ticket(s)**: Closes #362 
---
Renamed GithubKey to InertiaKey mentioned in url
https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/ubclaunchpad/inertia%24+githubKey
> refactor: rename references of GithubKey to InertiaKey

- Dockerfile
- Makefile
---
* Pin versions
* Address lint complaints
* Remove a build stage
* Clean up make script
`make daemon`
> chore: clean up dockerfile spec

- cmd/remote/remote.go
:tickets: **Ticket(s)**: Closes #700 
---
Simply added a new line to fix some output formatting!
N/A
> Add newline to fix output format

- cfg/identity.go
- cfg/internal/identity/identify.go
- contrib/README.md
- contrib/inertia-completions/main.go
- contrib/inertia-docgen/main.go
- daemon/inertiad/notify/doc.go
- local/git/doc.go
> docs: add missing package docs

- api/api.go
- api/response.go
- api/response_test.go
- cfg/remote.go
- client/client.go
- cmd/remote/remote.go
- cmd/remotes/user.go
- daemon/inertiad/auth/permissions.go
- daemon/inertiad/crypto/token.go
:tickets: **Ticket(s)**: Closes #699
---
Save last-logged-in user and improve advice for logging in
> cmd: improve reauthentication flow

- contrib/inertia-publish/assets.go
- contrib/inertia-publish/channels.go
- contrib/inertia-publish/generate.go
- contrib/inertia-publish/main.go
---
`inertia-publish` was kind of written in a hurry, this goes back and gives it some love.
n/a
> contrib(publish): clean up and document publishing tool
